services:

  db:
    image: postgres:16
    container_name: sentinel_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: sentinel_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: